# Generated by Django 2.2.7 on 2019-11-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_auto_20191116_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_subject_list',
            field=models.ManyToManyField(to='schoolapp.Teacher_subject'),
        ),
        migrations.AddField(
            model_name='teacher_subject',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Grade'),
        ),
        migrations.AddField(
            model_name='teacher_subject',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Stream'),
        ),
        migrations.AddField(
            model_name='teacher_subject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Subject'),
        ),
    ]
