# Generated by Django 2.2.7 on 2019-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20191116_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
