# Generated by Django 2.2.7 on 2019-11-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_timestamp_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='data_createdd',
            new_name='data_created',
        ),
    ]
