# Generated by Django 2.2.7 on 2019-11-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_auto_20191117_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='timestamp',
            new_name='exam_name',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
