# Generated by Django 2.2.7 on 2019-11-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20191117_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
    ]
