# Generated by Django 2.2.7 on 2019-11-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_remove_teacher_teacher_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
