# Generated by Django 2.2.7 on 2019-12-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Grade'),
        ),
        migrations.AddField(
            model_name='report',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Stream'),
        ),
    ]
