# Generated by Django 2.2.7 on 2019-12-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_auto_20191211_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectedTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Timestamp')),
            ],
        ),
    ]
