# Generated by Django 2.2.7 on 2019-12-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_selectedtimestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='selectedTimestamp',
            new_name='selectedItems',
        ),
    ]
