# Generated by Django 2.2.7 on 2019-12-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20191211_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='selectedItems',
            new_name='selectedItem',
        ),
    ]
