# Generated by Django 2.2.7 on 2019-12-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_auto_20191211_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecteditem',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
