# Generated by Django 2.2.7 on 2019-12-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0015_auto_20191211_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timestamp',
            options={'ordering': ['-id']},
        ),
        migrations.DeleteModel(
            name='selectedItem',
        ),
    ]
