# Generated by Django 2.2.7 on 2019-12-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0016_auto_20191212_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='selectedDatabase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Timestamp'),
        ),
    ]
