# Generated by Django 2.2.7 on 2019-12-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0019_teacher_selectedsubjectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='selectedSubjectId',
        ),
    ]
