# Generated by Django 2.2.7 on 2019-12-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0021_teacher_selectedsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='selectedDatabase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Timestamp'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='selectedSubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Subject'),
        ),
    ]
