# Generated by Django 2.2.7 on 2019-12-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0022_auto_20191223_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
