# Generated by Django 2.2.7 on 2020-01-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0027_auto_20191231_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
