# Generated by Django 2.2.7 on 2020-01-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0029_auto_20200101_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
