# Generated by Django 2.2.7 on 2020-01-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0030_teacher_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
    ]
