# Generated by Django 2.2.7 on 2020-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0031_remove_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='kiswahili',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='science',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='social_studies',
            field=models.IntegerField(null=True),
        ),
    ]
