# Generated by Django 2.2.7 on 2020-01-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0032_auto_20200108_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(null=True, to='schoolapp.Subject'),
        ),
    ]
