# Generated by Django 2.2.7 on 2020-01-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0033_student_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='Form',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='grade',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='grade',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='class_teacher_grade',
            new_name='class_teacher_form',
        ),
        migrations.RenameField(
            model_name='teacher_subject',
            old_name='grade',
            new_name='form',
        ),
    ]
