# Generated by Django 2.2.7 on 2020-01-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0036_report_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='cre',
            new_name='biology',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='science',
            new_name='bussiness',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='social_studies',
            new_name='chemistry',
        ),
        migrations.AddField(
            model_name='report',
            name='computer_studies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_exam_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
