# Generated by Django 2.2.7 on 2020-01-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0037_auto_20200111_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='agriculture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='cre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='geography',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='history',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='physics',
            field=models.IntegerField(null=True),
        ),
    ]
