# Generated by Django 2.2.7 on 2020-01-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0038_auto_20200111_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('upper_limit', models.IntegerField()),
                ('lower_limit', models.IntegerField()),
            ],
        ),
    ]
