# Generated by Django 2.2.7 on 2020-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0040_auto_20200112_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='compulsory',
            field=models.BooleanField(default=False),
        ),
    ]
